#macro TILE_SIZE 8
#macro TILEMAP_WIDTH 100
#macro TILEMAP_HEIGHT 62
#macro CANVAS_WIDTH 800
#macro CANVAS_HEIGHT 496
#macro NUM_CLIENTS_MAX 8
#macro PACKET_PIXEL 1
#macro PACKET_ERASEALL 2

#macro BRUSH_TYPE_PIXEL 0
#macro BRUSH_TYPE_SMALL 1
#macro BRUSH_TYPE_MEDIUM 2
#macro BRUSH_TYPE_LARGE 3
#macro BRUSH_TYPE_FILL 4
